version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: productcatalogadmin
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: productcatalogdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productcatalog-api
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DbConfig=Host=postgres;Database=productcatalogdb;Username=productcatalogadmin;Password=senha
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  postgres_data: